import { expect, test } from "@playwright/test";
import { actor, noOverflow, onboarding } from "./helpers";

test("initiator can be the receiving party: shared documents are read-only and personal documents remain private", async ({ browser }) => {
  const customer = await actor(browser, 72421, "+79997002421");
  const supplier = await actor(browser, 72422, "+79997002422");
  const first = await customer.newPage(), second = await supplier.newPage();
  await first.goto("/"); await onboarding(first);
  await second.goto("/"); await onboarding(second);
  await first.getByRole("button", { name: "Создать", exact: true }).click();
  await first.getByRole("tab", { name: "Готовые шаблоны" }).click();
  await first.getByRole("button", { name: /Аренда имущества/ }).click();
  const creating = first.waitForResponse(r => r.url().endsWith("/deals") && r.request().method() === "POST");
  await first.getByRole("button", { name: "Продолжить", exact: true }).click();
  const deal = await (await creating).json();
  await first.getByRole("textbox", { name: /^Краткое описание/ }).fill("Аренда комнаты: я арендатор, вторая сторона передаёт помещение.");
  await first.getByRole("combobox", { name: "Ваша роль в сделке" }).click();
  await first.getByRole("option", { name: "Арендатор", exact: true }).click();
  await first.getByRole("button", { name: "Сохранить и продолжить" }).click();
  await expect(first.getByRole("heading", { name: "Параметры сделки" })).toBeVisible();
  const current = await (await first.request.get(`/api/v1/deals/${deal.id}`)).json();
  expect(current.draft.subjectDocumentsParty).toBe("COUNTERPARTY");
  const invite = await (await first.request.post(`/api/v1/deals/${deal.id}/invitations`, { data: { expectedVersionId: current.versionId, expectedUpdatedAt: current.updatedAt } })).json();
  expect((await second.request.post("/api/v1/deal-invitations/join", { data: { publicCode: invite.publicCode, token: invite.shareUrl.split("#")[1] } })).ok()).toBe(true);
  const url = `/api/v1/deals/${deal.id}/files`;
  const customerFiles = await (await first.request.get(url)).json();
  const supplierFiles = await (await second.request.get(url)).json();
  expect(customerFiles.canUploadEvidence).toBe(false);
  expect(supplierFiles.canUploadEvidence).toBe(true);
  const property = customerFiles.requirements.find((r: { title: string }) => r.title === "Документ на имущество");
  const personal = customerFiles.requirements.find((r: { title: string }) => r.title.includes("личность"));
  expect(property.canUpload).toBe(false);
  expect(personal.canUpload).toBe(true);
  const file = { name: "synthetic.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.7 synthetic") };
  expect((await first.request.post(url, { multipart: { category: "EVIDENCE", file } })).status()).toBe(403);
  expect((await first.request.post(url, { multipart: { category: "REQUIREMENT", requirementId: property.id, file } })).status()).toBe(403);
  const own = await first.request.post(url, { multipart: { category: "REQUIREMENT", requirementId: personal.id, file } });
  expect(own.ok()).toBe(true);
  expect((await second.request.get(`${url}/${(await own.json()).id}/content`)).status()).toBe(404);
  const shared = await second.request.post(url, { multipart: { category: "REQUIREMENT", requirementId: property.id, file } });
  expect(shared.ok()).toBe(true);
  expect((await first.request.get(`${url}/${(await shared.json()).id}/content`)).ok()).toBe(true);
  await first.goto(`/?WebAppStartParam=deal_${deal.id.replaceAll("-", "")}`);
  await first.getByRole("button", { name: "Документы сделки" }).click();
  await expect(first.getByRole("button", { name: "Добавить материалы" })).toHaveCount(0);
  await expect(first.locator(".requirement-upload-card").filter({ hasText: "Документ на имущество" }).getByRole("button")).toHaveCount(0);
  await noOverflow(first);
  await customer.close(); await supplier.close();
});
